[package]
name = "popeinput-rime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "RIME (librime) input engine for popeinput"

[dependencies]
popeinput-engine = { path = "../engine" }
rime-sys = { path = "../rime-sys" }
log = "0.4"
